spring:
  datasource:
    url: jdbc:h2:mem:jwtdb
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect